export const blogData = [
  {
    id: 1,
    slug: "zomato-makes-history",
    title:
      "Sensex Zomato: What's Driving Zomato's Performance on the BSE Sensex?",
    desc: "Explore Zomato's impact on the BSE Sensex and business growth insights.",
    date: "2024-12-25",
    tags: ["News", "Finance"],
    category: ["finance", "news"],
    readTime: "5 min read",
    featured: true,
  },
  {
    id: 2,
    slug: "chatgpt-business-2026",
    title: "How ChatGPT is Transforming Business in 2026",
    desc: "How AI and ChatGPT are revolutionizing MSMEs and startups.",
    date: "2026-05-25",
    tags: ["AI", "Business Growth"],
    category: ["ai", "business"],
    readTime: "8 min read",
    featured: true,
  },
  {
    id: 3,
    slug: "prompt-engineering-guide",
    title: "How to Become a Prompt Engineer in AI (2026 Guide)",
    desc: "Complete roadmap, skills, salary, and career guide for prompt engineers.",
    date: "2026-06-10",
    tags: ["AI", "Career", "Prompt Engineering"],
    category: ["ai", "career"],
    readTime: "12 min read",
    featured: true,
  },
  {
    id: 4,
    slug: "digital-marketing-startups",
    title: "Digital Marketing Strategies for Startups in 2026",
    desc: "Learn cost-effective digital marketing tactics for early-stage startups.",
    date: "2026-04-15",
    tags: ["Marketing", "Startups"],
    category: ["marketing", "business"],
    readTime: "6 min read",
    featured: false,
  },
  {
    id: 5,
    slug: "blockchain-future",
    title: "Blockchain Technology: Future of Secure Transactions",
    desc: "Understanding blockchain's impact on finance and data security.",
    date: "2026-03-20",
    tags: ["Technology", "Finance"],
    category: ["technology", "finance"],
    readTime: "10 min read",
    featured: false,
  },
];
